services:
  zipkin-all-in-one:
    image: openzipkin/zipkin:latest
    restart: always
    ports:
      - "9411:9411"

  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./.docker/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317" # Porta padrão para gRPC
      - "55680:55680" # Porta padrão para Zipkin

  zip-code-validation:
    build:
      context: ./services/zip-code-validation
      dockerfile: Dockerfile
    environment:
      - SERVICE_NAME=zip-code-validation
      - TEMPERATURE_SERVICE_URL=http://temperature-service:8081
      - PORT=8080
      - OTEL_RESOURCE_ATTRIBUTES=service.name=validation,service.version=0.0.1
    ports:
      - "8080:8080"
    volumes:
      - ./services/zip-code-validation:/app
    depends_on:
      - temperature-service
      - otel-collector
      - zipkin-all-in-one

  temperature-service:
    build:
      context: ./services/temperature
      dockerfile: Dockerfile
    environment:
      - SERVICE_NAME=temperature-service
      - CEP_SERVICE_URL=https://brasilapi.com.br/api/cep/v2
      - WEATHER_API_URL=https://api.weatherapi.com/v1/current.json
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - PORT=8081
      - OTEL_RESOURCE_ATTRIBUTES=service.name=temperature,service.version=0.0.1
      - OTEL_COLLECTOR_URL=http://otel-collector:4317
    ports:
      - "8081:8081"
    volumes:
      - ./services/temperature:/app
    depends_on:
      - otel-collector
      - zipkin-all-in-one
