### Invalid code
POST http://localhost:8080//zipcode
Content-Type: application/json

{
  "cep": 10
}

### Valid
POST http://localhost:8080//zipcode
Content-Type: application/json

{
  "cep": "79310541"
}